HW09 is completed
codereav/go-homework pull request #11
Opened 2023-09-04 20:36 UTC by codereav

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-09-08 20:05 UTC, ityulkanov requested changes
Я бы рекомендовал доработать логику чтобы она учитывала ещё и тип поля. Сейчас уже неплохо, но при добавлении дополнительных типов некоторые из ошибок могут вводить в заблуждение. Т.е. я бы как минимум тогда бы возвращал для min max на string поле incorrect field type и для regexp на int

2023-09-08 20:05 UTC, ityulkanov commented on hw09_struct_validator/validator.go
> +		formattedRuleValue, err := strconv.Atoi(ruleValue)
кмк всё же стоило бы разделять поведение валидаторов в зависимости от типа обрабатываемого поля, сейчас тот же regexp которому попадётся числовое поле просто вернёт "не проходит по regexp" хотя мы возможно искали вхождения строк определённых. Т.е. вводит в заблуждение end users либа.

2023-09-11 19:40 UTC, codereav commented on hw09_struct_validator/validator.go
> +		formattedRuleValue, err := strconv.Atoi(ruleValue)
Сделал небольшой рефакторинг - добавил указание доступных валидаторов для типов, добавил проверку на совместимость, сделал ошибки более информативными. Запушил отдельным [коммитом](https://github.com/codereav/go-homework/pull/11/commits/448c420183fba8c55febee5abeaca7363ea0dd96).

2023-09-12 08:51 UTC, ityulkanov approved these changes

2023-09-12 09:04 UTC, merged